# k8s-config/1-infraestrutura/mongo-config.yml
# (Baseado no Lab5.docx)
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: grupo2
data:
  # Service Discovery din치mico - K8s resuelve autom치ticamente el IP
  # Solo host:puerto (sin mongodb://) ya que el c칩digo a침ade ese prefijo
  mongo-url: mongo-service.grupo2.svc.cluster.local:27017