# k8s-config/1-infraestrutura/mongo-config.yml
# (Baseado no Lab5.docx)
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: grupo2
data:
  # O nome 'mongo-service' deve ser o mesmo do 'kind: Service' abaixo
  mongo-url: mongo-service