apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace compartido para todos los recursos
namespace: grupo2

# Recursos de la aplicaci√≥n (base)
resources:
  - api.yml
  - consumidor.yml
  - produtor.yml
  - ui.yml
  - hpa.yml
